// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyeuktekkdcfivhwuqcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5ZXVrdGVra2RjZml2aHd1cWNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMDc5MzAsImV4cCI6MjA3MDY4MzkzMH0.hUes1ELUYcdOv5hzUQxQSFAEL6-xVYnatL7wBTdWuzw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});